#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Holberton School\n" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
