#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Holberton School\n" | sudo tee /var/www/html/index.html
service nginx restart
