#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

sudo apt-get -y update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "<h1>Hello World!</h1>" > /var/www/html/index.nginx-debian.html
service nginx restart
