#!/usr/bin/env bash
#configure a new server

sudo apt-get update
sudo apt-get -y install nginx
sudo systemctl start nginx.service
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
