#!/usr/bin/env bash
# Installs, configures, and starts the load balancer

sudo apt-get update
sudo apt-get -y install haproxy

echo "
frontend myfrontend
	bind *:80
	default_backend myservers

backend myservers
	balance roundrobin
	server 88798-web-01 3.86.18.132:80 check
	server 88798-web-02 18.204.14.144:80 check
" >> /etc/haproxy/haproxy.cfg

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	service haproxy start
else
	service haproxy restart
fi
