#!/usr/bin/env bash
#script that pings an IP address passed as an argument

IP="${1}"
host=$(basename "${BASH_SOURCE[@]}")
if ! [ "$IP" ]; 
	then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
