#!/usr/bin/env bash
#aaaaa

touch /var/run/myscript.pid
delete_and_exit()
{
   rm /var/run/holbertonscript.pid;
   exit
}
trap "echo 'I hate the kill command'; delete_and_exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "delete_and_exit" SIGQUIT
while true
do
        echo "To infinity and beyond"
	sleep 2
done
