#!/usr/bin/env bash
#This script is displaying "Best School" 10 times

i=1
j=4
k=8
while [ $i -le 10 ]
do
  if (( i == j ))
  then
  echo bad luck
  elif [ i == k ]
  then
  echo good luck
  else
  echo Best School
  fi
  
  ((i++))
done
