#!/usr/bin/env bash
#localhost resolves to 127.0.0.
#facebook.com from 157.240.11.35 to 8.8.8.8

cp /etc/hosts ~/new_hosts
echo "127.0.0.2		localhost" > ~/new_hosts
echo "8.8.8.8		facebook.com" >> ~/new_hosts
cp -f ~/new_hosts /etc/hosts
