#!/usr/bin/env bash
# changing from root to nginx user
chmod 640 /etc/nginx
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
