#!/usr/bin/env bash
# changing from root to nginx user
pkill -f apache2
sudo service nginx start
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo service nginx restart
